// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChMM-mRJ4YR1TWSJvk3079gLQQYQpz2fM',
    appId: '1:221346516430:web:b3d35fef3c44f8487f6f9f',
    messagingSenderId: '221346516430',
    projectId: 'testing-39fd8',
    authDomain: 'testing-39fd8.firebaseapp.com',
    storageBucket: 'testing-39fd8.appspot.com',
    measurementId: 'G-RRZ9W0WBES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCezhRDvFNEbxF5cmpf3DA61ZB2Xi-AgXg',
    appId: '1:436415735484:android:6ee8972a8b63f2b7e692b9',
    messagingSenderId: '436415735484',
    projectId: 'sparkie-new-project',
    storageBucket: 'sparkie-new-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqv7zFHPdTf9aNmUCQ2kLG5gADNP7qr5E',
    appId: '1:436415735484:ios:45980e1d59d32777e692b9',
    messagingSenderId: '436415735484',
    projectId: 'sparkie-new-project',
    storageBucket: 'sparkie-new-project.appspot.com',
    iosBundleId: 'com.greenFund',
  );
}